### ISSUE TITLE
nonBlank and required

### ISSUE THREAD

**Issue by albertstevelino** [cermati/satpam#34]
does nonBlank and required would work the same way? if you put required, then normally we would expect not to put some white space only in the field. so i suggest we should remove nonBlank validation and put trim on required. that way we would not have two duplicate validation that sould work the same way.

issues:
if you put required and nonBlank together they would produce two duplicate error since nonBlank using the required logic. they would have two different key error with the same error value.

since most of our credit card form using required validation, it would not check empty space only. i.e. if you put only space on your name in application form, it would pass the validation. THIS SHOULD NOT BE HAPPENED!

**Comment by sendyhalim** [comment]
Short answer
Yes agree, good point

Long answer
First of all, we decided to make `satpam` as minimal as possible, leaving the responsibility to trim the input to software engineers because `satpam` responsibility is only to **validate** and not trimming. As time goes by, this would complicate things (life happens, the ideal situation is hard to accomplish, I guess that's why we call it the ideal world 🏖 ).

https://github.com/illuminate/validation/blob/970aec1cdb425ca7114b313c590e6a011edda156/Concerns/ValidatesAttributes.php#L1026

Steps that need to be taken
- We should make a PR for this changes
- Bump `satpam` major version because this would be included in breaking changes
- Publish to npm
